package au.gov.qld.idm.neo.identity.model.dynamo;

import au.gov.qld.idm.neo.converters.ZonedDateTimeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.ZonedDateTime;

/**
 * Project qgc-idm-application
 * Created on 08 Jan 2018.
 */
@DynamoDBTable(tableName = "CustomerAttributes")
public class CustomerAttributeRecord {
    private String recordId;
    private ZonedDateTime creationDateTime;
    private String qid;
    private String attributeName;
    private String attributeValue;

    @DynamoDBHashKey(attributeName = "record_id")
    @DynamoDBAutoGeneratedKey
    @JsonProperty("record_id")
    public String getRecordId() {
        return recordId;
    }

    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    @DynamoDBTypeConverted(converter = ZonedDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "creation_date_time")
    @JsonProperty("creation_date_time")
    public ZonedDateTime getCreationDateTime() {
        return creationDateTime;
    }

    public void setCreationDateTime(ZonedDateTime creationDateTime) {
        this.creationDateTime = creationDateTime;
    }

    @DynamoDBAttribute(attributeName = "qid")
    public String getQid() {
        return qid;
    }

    public void setQid(String qid) {
        this.qid = qid;
    }

    @DynamoDBAttribute(attributeName = "attribute_name")
    @JsonProperty("attribute_name")
    public String getAttributeName() {
        return attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    @DynamoDBAttribute(attributeName = "attribute_value")
    @JsonProperty("attribute_value")
    public String getAttributeValue() {
        return attributeValue;
    }

    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }
}
