package au.gov.qld.idm.neo.evidenceofidentity.model.dynamo;

import au.gov.qld.idm.neo.converters.ZonedDateTimeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.ZonedDateTime;


/**
 * Project qgc-idm-application
 * Created on 08 Jan 2018.
 */

@DynamoDBTable(tableName = "VerificationItem")
//@DynamoDBDocument
public class VerificationItem {
	
	private String verificationItemId;
	
	public VerificationItem() {
		verificationItemId = "";
	}

}
